application : test
runtime : python27
version : 1
api_version : 1
threadsafe : true

handlers:

- url : /v1/sms/.*
  script : app.api.sms.app
  secure : always

- url : /v1/users/.*
  script : app.api.user.app
  secure : always

- url : /v1/users
  script : app.api.user.app
  secure : always