application : test
runtime : python27
version : 1
api_version : 1
threadsafe : true

handlers:

- url : /v1/sms/broadcast
  script : app.api.sms.broadcast.app
  secure : always

- url : /v1/sms/.*
  script : app.api.sms.app
  secure : always

- url : /v1/users/.*
  script : app.api.user.app
  secure : always

- url : /v1/users
  script : app.api.user.app
  secure : always

- url : /v1/districts
  script : app.api.district.app
  secure : always

- url : /v1/districts/.*
  script : app.api.district.app
  secure : always

- url : /v1/config
  script : app.api.config.app
  secure : always
  login : admin

skip_files:
- tmp/.*
- venv/.*
- git_hooks/.*
- .*pyc
